### ISSUE TITLE
Adding more diodes to standard.dio

### ISSUE THREAD

**Issue by ltspicer** [evenator/LTSpice-Libraries#1]
If I complete the standard.dio with other diodes, LTspice (under Windows) will not show it to me.
LTspice under WINE (Linux) i can see the added diodes (Pick a new diode).
It exists a other/2nd path than LTspiceXVII/lib/cmp ?

Edit:
standard.dio open with LTspice, add new models and save that with LTspice solve the problem.

**Comment by HiTechSoldier** [comment]
Yup, gotta save with LTspice so it updates the lib files. Thanks for help
